//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool4You.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antwort
    {
        public Antwort()
        {
            this.Votum = new HashSet<Votum>();
        }
    
        public int Id { get; set; }
        public string Antowrttext { get; set; }
        public string Kommentar { get; set; }
        public int FrageId { get; set; }
    
        public virtual Frage Frage { get; set; }
        public virtual ICollection<Votum> Votum { get; set; }
    }
}
