//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool4You.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frage
    {
        public Frage()
        {
            this.Antwort = new HashSet<Antwort>();
        }
    
        public int Id { get; set; }
        public string Fragetext { get; set; }
        public string Fragetyp { get; set; }
        public int UmfrageId { get; set; }
    
        public virtual ICollection<Antwort> Antwort { get; set; }
        public virtual Umfrage Umfrage { get; set; }
    }
}
