//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool4You.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(UmfrageMetadata))]
    public partial class Umfrage
    {
        public Umfrage()
        {
            this.Frage = new HashSet<Frage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<System.DateTime> Start_Termin { get; set; }
        public Nullable<System.DateTime> End_Termin { get; set; }
        public string AspNetUsersId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Frage> Frage { get; set; }
    }
}
